version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: wallapop_mongo
    restart: unless-stopped
    ports:
      - "27000:27017"
    environment:
      MONGO_INITDB_DATABASE: wallapop_tracker
    volumes:
      - ./data/db:/data/db
